version: "3.9"

services:
    flask:
        build: .
        restart: unless-stopped
        volumes:
            - '.:/code'
        command: gunicorn -w 4 -b 0.0.0.0 'app:app'
        ports:
            - "8844:8000"

    redis:
        image: redis:7.0-alpine
        restart: unless-stopped

    celery:
        build: .
        restart: unless-stopped
        volumes:
            - '.:/code'
        command: celery -A tasks worker -l info
        depends_on:
            - redis

    celery_beat:
        build: .
        restart: unless-stopped
        volumes:
            - '.:/code'
        command: celery -A tasks beat -l info
        depends_on:
            - redis
            - celery
