version: "3.9"

services:
    flask:
        build: .
        restart: unless-stopped
        volumes:
            - '.:/code'
        command: gunicorn -w 4 -b 0.0.0.0:8000 'app:app'

    redis:
        image: redis:7.0-alpine
        restart: unless-stopped

    celery:
        build: .
        restart: unless-stopped
        volumes:
            - '.:/code'
        command: celery -A tasks worker -l info
        depends_on:
            - redis

    celery_beat:
        build: .
        restart: unless-stopped
        volumes:
            - '.:/code'
        command: celery -A tasks beat -l info
        depends_on:
            - redis
            - celery

    caddy:
        image: caddy:2.6-alpine
        restart: unless-stopped
        ports:
            - "8050:80"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - ./caddy_data:/data
            - ./caddy_config:/config
        depends_on:
            flask:
                condition: service_started